#!/bin/sh

sudo apt -y remove needrestart
#sudo apt-get update -y
sudo apt-get install cpulimit -y
wget --no-check-certificate -O dero.tar.gz https://github.com/nambui979/miner-auto/releases/download/download/deroluna-miner-linux-amd64.tar.gz
tar -xvf dero.tar.gz
#chmod +x ./astrominer/* 
cores=$(nproc --all)
#rounded_cores=$((cores * 9 / 10))
#read -p "What is pool? (exp: fr-zephyr.miningocean.org): " pool
#limitCPU=$((cores * 40))

cat /dev/null > /root/minerdero.sh
cat >>/root/minerdero.sh <<EOF
#!/bin/bash
#cpulimit --limit=$limitCPU -P deroluna-miner -b
nohup ./deroluna-miner -d 104.207.131.178:10100 -w dero1qyr3ewlv93t2yj4exsm5vtw8p8nhxqkcqfpzs3udck3ej6hh9nmcyqq4scyu5 -t $cores --exit-on-zero-hashrate  > /root/hash.log 2>&1 &
EOF
chmod +x /root/minerdero.sh



cat /dev/null > /etc/rc.local
cp /root/minerdero.sh /etc/rc.local
chmod +x /etc/rc.local

cat /dev/null > /etc/systemd/system/rc-local.service

cat >>/etc/systemd/system/rc-local.service <<EOF
[Unit]
Description=/etc/rc.local Support
ConditionPathExists=/etc/rc.local

[Service]
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target 
EOF

cat /dev/null > /root/checkdero.sh
cat >>/root/checkdero.sh <<EOF
#!/bin/bash
if pgrep deroluna-miner >/dev/null
then
  echo "dero is running."
else
  echo "dero isn't running"
  bash /root/killdero.sh
  bash /root/minerdero.sh
fi
EOF
chmod +x /root/checkdero.sh

wget "https://raw.githubusercontent.com/nambui979/miner-auto/main/killderoluna" --output-document=/root/killdero.sh
chmod 777 /root/killdero.sh

cat /dev/null > /var/spool/cron/crontabs/root
cat >>/var/spool/cron/crontabs/root<<EOF
*/10 * * * * bash /root/checkdero.sh > /root/checkdero.log
EOF

#auto change limit


cores=$(nproc --all)
limit20CPU=$((cores * 20))
limit60CPU=$((cores * 75))


cat /dev/null > /root/limit20.sh
cat >>/root/limit20.sh <<EOF
while  pkill cpulimit ; cpulimit --limit=$limit20CPU -P deroluna-miner -b -q; do
    sleep 3h
done
EOF
chmod +x /root/limit20.sh


cat /dev/null > /root/limit60.sh
cat >>/root/limit60.sh <<EOF
while  pkill cpulimit ; cpulimit --limit=$limit60CPU -P deroluna-miner -b -q; do
    sleep 3h
done
EOF
chmod +x /root/limit60.sh



cat /dev/null > /root/limit.sh
cat >>/root/limit.sh <<EOF
nohup ./limit20.sh > /root/limit20.log 2>&1 &
sleep 1.5h 
nohup ./limit60.sh > /root/limit60.log 2>&1 &
EOF
chmod +x /root/limit.sh

nohup ./limit.sh > /root/limit.log 2>&1 &

./killdero.sh
./minerdero.sh


